import dotenv from "dotenv";
dotenv.config();

export const DEVNET_CONFIG = {
  TENDERLY_ACCOUNT_ID: process.env.TENDERLY_ACCOUNT_ID,
  TENDERLY_PROJECT_SLUG: process.env.TENDERLY_PROJECT_SLUG,
  TENDERLY_MAINNET_DEVNET_TEMPLATE:
    process.env.TENDERLY_MAINNET_DEVNET_TEMPLATE,
  TENDERLY_OPTIMISM_DEVNET_TEMPLATE:
    process.env.TENDERLY_OPTIMISM_DEVNET_TEMPLATE,
  TENDERLY_ARBITRUM_DEVNET_TEMPLATE:
    process.env.TENDERLY_ARBITRUM_DEVNET_TEMPLATE,
};
